# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mranyone/Documents/Projects/tads2016/augusto/c/trabalhos/2_space_invaders

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mranyone/Documents/Projects/tads2016/augusto/c/trabalhos/2_space_invaders

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mranyone/Documents/Projects/tads2016/augusto/c/trabalhos/2_space_invaders/CMakeFiles /home/mranyone/Documents/Projects/tads2016/augusto/c/trabalhos/2_space_invaders/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mranyone/Documents/Projects/tads2016/augusto/c/trabalhos/2_space_invaders/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named space_debug

# Build rule for target.
space_debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 space_debug
.PHONY : space_debug

# fast build rule for target.
space_debug/fast:
	$(MAKE) -f CMakeFiles/space_debug.dir/build.make CMakeFiles/space_debug.dir/build
.PHONY : space_debug/fast

#=============================================================================
# Target rules for targets named space_invaders

# Build rule for target.
space_invaders: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 space_invaders
.PHONY : space_invaders

# fast build rule for target.
space_invaders/fast:
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/build
.PHONY : space_invaders/fast

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/space_debug.dir/build.make CMakeFiles/space_debug.dir/main.o
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/space_debug.dir/build.make CMakeFiles/space_debug.dir/main.i
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/space_debug.dir/build.make CMakeFiles/space_debug.dir/main.s
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/main.s
.PHONY : main.s

# target to build an object file
spcinv/spcinv.o:
	$(MAKE) -f CMakeFiles/space_debug.dir/build.make CMakeFiles/space_debug.dir/spcinv/spcinv.o
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/spcinv/spcinv.o
.PHONY : spcinv/spcinv.o

# target to preprocess a source file
spcinv/spcinv.i:
	$(MAKE) -f CMakeFiles/space_debug.dir/build.make CMakeFiles/space_debug.dir/spcinv/spcinv.i
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/spcinv/spcinv.i
.PHONY : spcinv/spcinv.i

# target to generate assembly for a file
spcinv/spcinv.s:
	$(MAKE) -f CMakeFiles/space_debug.dir/build.make CMakeFiles/space_debug.dir/spcinv/spcinv.s
	$(MAKE) -f CMakeFiles/space_invaders.dir/build.make CMakeFiles/space_invaders.dir/spcinv/spcinv.s
.PHONY : spcinv/spcinv.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... space_debug"
	@echo "... space_invaders"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... spcinv/spcinv.o"
	@echo "... spcinv/spcinv.i"
	@echo "... spcinv/spcinv.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

